name: variant-pipeline
dependencies:
  - python=2.7.13   # or 2.7
  - pandas=0.19.2
  - biopython=1.68
  - numpy=1.11
  - bioconda::bowtie2
  - bioconda::fastqc=0.10.1
  - bioconda::muscle=3.8.31
  - pip: 
    - pysam==0.11.1
    - cutadapt==1.13
    - pyyaml==3.12
